"""
Lista de los ERDS usados
"""
Erd_BuildNumber                         =   "0031"
Erd_Reset                               =   "0032"
Erd_BootLoaderVersion                   =   "0039"
Erd_ApplicationVersion                  =   "003A"
Erd_ParametricVersion                   =   "003B"
Erd_GitHash                             =   "007F"
Erd_ResetCount                          =   "0700"
Erd_LaundryCurrentSelectedCycle         =   "200A"
Erd_WarmRinseOption                     =   "2025"
Erd_ControlLockOption                   =   "2083"
Erd_AutoSoakLevelOption                 =   "20AB"
Erd_DeepFillIncrementalOption           =   "20AD"
Erd_DelayWashOption                     =   "20B1"
Erd_ExtraRinseOption                    =   "20B3"
Erd_FabricSoftenerOption                =   "20B5"
Erd_SpinLevelOption                     =   "20B7"    
Erd_WaterTemperatureOption              =   "20BB"
Erd_SoilLevelOption                     =   "20BE"
Erd_WaterOnDemandSoapDispenseOption     =   "20B9"
Erd_StainRemovalGuideOption             =   "20CF"
Erd_MbKeyStatusWord                     =   "F01B"
Erd_MabeCommunicationConfiguration      =   "F011"
Erd_MabeCommunicationRequest1Levels     =   "F015"
Erd_MabeCommunicationRequest2Units      =   "F018"
Erd_MabeCommunicationRequest2Icons      =   "F019"
Erd_UI_MachineStateEnter                =   "F06A"
Erd_UI_MachineStateExit                 =   "F06B"
Erd_UI_CycleSelection                   =   "F06C"
Erd_MC_CycleEngineActualState           =   "F070"
Erd_MC_CycleEngineRequestState          =   "F071"
Erd_MC_CycleCount                       =   "F095"
Erd_EndOfCycleReason                    =   "F097"
Erd_CriticalFault                       =   "F09D"
Erd_OredShutDownUIFaults                =   "F117"